apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mern.fullname" . }}-backend
  labels:
    app.kubernetes.io/component: backend
    {{- include "mern.labels" . | nindent 4 }}
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
      {{- include "mern.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.backend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: backend
        {{- include "mern.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mern.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.backend.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}-backend
        securityContext:
          {{- toYaml .Values.backend.securityContext | nindent 12 }}
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - name: {{ include "mern.fullname" . }}-backend
          containerPort: {{ .Values.frontend.service.containerPort }}
          protocol: TCP
        env:
        - name: SERVER
          valueFrom:
            secretKeyRef:
              name: {{ include "mern.fullname" . }}-backend
              key: mongo
        livenessProbe:
          httpGet:
            path: /todos
            port: {{ .Values.backend.service.containerPort }}
        readinessProbe:
          httpGet:
            path: /todos
            port: {{ .Values.backend.service.containerPort }}
        resources:
          {{- toYaml .Values.backend.resources | nindent 12 }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}