apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mern.fullname" . }}-backend
  labels:
    app.kubernetes.io/component: backend
    {{- include "mern.labels" . | nindent 4 }}
type: Opaque
stringData:
  mongo: mongodb://admin:danmerasahina@mern-mongodb:27017/todos