apiVersion: v1
kind: Service
metadata:
  name: {{ include "mern.fullname" . }}-frontend
  labels:
    app.kubernetes.io/component: frontend
    {{- include "mern.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.servicePort }}
    targetPort: {{ .Values.frontend.service.containerPort }}
    protocol: TCP
    name: {{ include "mern.fullname" . }}-frontend
  selector:
    app.kubernetes.io/component: frontend
    {{- include "mern.selectorLabels" . | nindent 4 }}