apiVersion: v1
kind: Service
metadata:
  name: {{ include "mern.fullname" . }}-mongodb
  labels:
    app.kubernetes.io/component: mongodb
    {{- include "mern.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mongodb.service.type }}
  ports:
  - port: {{ .Values.mongodb.service.servicePort }}
    targetPort: {{ .Values.mongodb.service.containerPort }}
    protocol: TCP
    name: {{ include "mern.fullname" . }}-mongodb
  selector:
    app.kubernetes.io/component: mongodb
    {{- include "mern.selectorLabels" . | nindent 4 }}